#!/usr/bin/env python3
"""Check and sync Bears canonical agent TOMLs into Codex agent directories."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
CANONICAL_AGENT_DIR = PLUGIN_ROOT / "agents"
PLATFORM_ROLE_CATALOG = PLUGIN_ROOT / "assets/catalog/platform-role-catalog.v1.json"
USER_TARGET_REL = Path(".codex/agents")
REPO_TARGET_REL = Path(".codex/agents")
MANAGED_HEADER = "# Generated by Bears agent_registration_sync.py."
SOURCE_HEADER = "# Source-Path: "
DIGEST_HEADER = "# Source-Digest-SHA256: "
MANAGED_DIGEST_HEADER = "# Managed-Digest-SHA256: "
REQUIRED_CODEX_FIELDS = ("name", "description", "developer_instructions")
REQUIRED_BEAR_FIELDS = ("model", "model_reasoning_effort", "sandbox_mode")
REQUIRED_ROLE_CLASSIFICATION_FIELDS = ("role_kind", "execution_class", "primary_eligible")
ROLE_KINDS = {"specialist", "helper", "reviewer", "orchestrator"}
EXECUTION_CLASSES = {"specialist", "helper"}
REQUIRED_DEVELOPER_INSTRUCTION_MARKERS = (
    "Working mode:",
    "Scope/focus:",
    "Forbidden actions:",
    "Quality checks:",
    "Return shape:",
    "Validation expectations:",
)
ROLE_OVERRIDE_PREFIX = "- Role override: "
ALLOWED_TARGETS = ("user", "repo")
TOOL_SCHEMA_REFRESH_REQUIRED_STATUS = "runtime_tool_schema_refresh_required"


@dataclass(frozen=True)
class CanonicalAgent:
    """Canonical source agent with the destination name used by Codex."""

    source_path: Path
    destination_name: str
    body: str
    digest: str

    @property
    def destination_file(self) -> str:
        """Return the target file name for this custom agent."""
        return f"{self.destination_name}.toml"


def sha256_text(text: str) -> str:
    """Return a SHA-256 digest for UTF-8 text."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _rel_source(path: Path) -> str:
    try:
        return path.resolve().relative_to(PLUGIN_ROOT.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def validate_developer_instruction_markers(path: Path, developer_instructions: str) -> list[str]:
    """Validate required shared policy markers in one agent instruction block."""
    errors: list[str] = []
    instruction_lines = {line.strip() for line in developer_instructions.splitlines()}
    for marker in REQUIRED_DEVELOPER_INSTRUCTION_MARKERS:
        if marker not in instruction_lines:
            errors.append(f"{_rel_source(path)} missing required developer_instructions marker: {marker}")
    return errors


def validate_developer_instruction_role_override(path: Path, data: dict[str, Any]) -> list[str]:
    """Validate that one agent instruction block binds to its own role entity."""
    errors: list[str] = []
    name = data.get("name")
    description = data.get("description")
    developer_instructions = data.get("developer_instructions")
    if not all(isinstance(value, str) and value.strip() for value in (name, description, developer_instructions)):
        return errors
    required_name_marker = f"Operate as `{name}`"
    if required_name_marker not in developer_instructions:
        errors.append(
            f"{_rel_source(path)} developer_instructions must include exact role marker: {required_name_marker}"
        )
    if description not in developer_instructions:
        errors.append(
            f"{_rel_source(path)} developer_instructions must include exact role description override"
        )
    required_override_line = f"{ROLE_OVERRIDE_PREFIX}{description}"
    instruction_lines = {line.strip() for line in developer_instructions.splitlines()}
    if required_override_line not in instruction_lines:
        errors.append(
            f"{_rel_source(path)} developer_instructions must include exact role override line: "
            f"{required_override_line}"
        )
    return errors


def build_role_audit_packet(agents: list[CanonicalAgent], schema_errors: list[str]) -> dict[str, Any]:
    """Build a deterministic sequential audit packet for every canonical agent role."""
    sequence: list[dict[str, Any]] = []
    failed_agents = 0
    failures: list[dict[str, Any]] = []
    for index, agent in enumerate(sorted(agents, key=lambda item: _rel_source(item.source_path)), start=1):
        data = tomllib.loads(agent.body)
        agent_errors: list[str] = []
        developer_instructions = data.get("developer_instructions")
        if isinstance(developer_instructions, str) and developer_instructions.strip():
            agent_errors.extend(validate_developer_instruction_markers(agent.source_path, developer_instructions))
            agent_errors.extend(validate_developer_instruction_role_override(agent.source_path, data))
        else:
            agent_errors.append(f"{_rel_source(agent.source_path)} missing developer_instructions")
        status = "pass" if not agent_errors else "fail"
        if agent_errors:
            failed_agents += 1
            failures.append(
                {
                    "agent_file": _rel_source(agent.source_path),
                    "name": data.get("name"),
                    "errors": agent_errors,
                }
            )
        sequence.append(
            {
                "index": index,
                "agent_file": _rel_source(agent.source_path),
                "name": data.get("name"),
                "role_kind": data.get("role_kind"),
                "execution_class": data.get("execution_class"),
                "primary_eligible": data.get("primary_eligible"),
                "model": data.get("model"),
                "model_reasoning_effort": data.get("model_reasoning_effort"),
                "sandbox_mode": data.get("sandbox_mode"),
                "status": status,
                "errors": agent_errors,
            }
        )
    all_errors = [*schema_errors, *[error for failure in failures for error in failure["errors"]]]
    return {
        "schema": "bears-agent-role-audit.v1",
        "status": "pass" if not all_errors else "fail",
        "audit_order": "lexicographic_agent_file_path",
        "canonical_agents": len(agents),
        "failed_agents": failed_agents + (1 if schema_errors else 0),
        "failures": failures,
        "schema_errors": schema_errors,
        "sequence": sequence,
    }


def load_canonical_agents(agent_dir: Path = CANONICAL_AGENT_DIR) -> tuple[list[CanonicalAgent], list[str]]:
    """Load canonical agent TOMLs and return validation errors."""
    agents: list[CanonicalAgent] = []
    errors: list[str] = []
    seen_names: dict[str, Path] = {}

    if not agent_dir.is_dir():
        return [], [f"canonical agent dir not found: {agent_dir}"]

    for path in sorted(agent_dir.glob("*.toml")):
        body = path.read_text(encoding="utf-8")
        try:
            data = tomllib.loads(body)
        except tomllib.TOMLDecodeError as exc:
            errors.append(f"{_rel_source(path)} TOML parse error: {exc}")
            continue

        for field in REQUIRED_CODEX_FIELDS:
            if not isinstance(data.get(field), str) or not data[field].strip():
                errors.append(f"{_rel_source(path)} missing required Codex custom-agent field: {field}")
        for field in REQUIRED_BEAR_FIELDS:
            if not isinstance(data.get(field), str) or not data[field].strip():
                errors.append(f"{_rel_source(path)} missing required Bears agent field: {field}")
        for field in REQUIRED_ROLE_CLASSIFICATION_FIELDS:
            if field not in data:
                errors.append(f"{_rel_source(path)} missing required role classification field: {field}")
        role_kind = data.get("role_kind")
        execution_class = data.get("execution_class")
        primary_eligible = data.get("primary_eligible")
        if role_kind is not None and role_kind not in ROLE_KINDS:
            errors.append(f"{_rel_source(path)} role_kind must be one of {sorted(ROLE_KINDS)}")
        if execution_class is not None and execution_class not in EXECUTION_CLASSES:
            errors.append(f"{_rel_source(path)} execution_class must be one of {sorted(EXECUTION_CLASSES)}")
        if "primary_eligible" in data and not isinstance(primary_eligible, bool):
            errors.append(f"{_rel_source(path)} primary_eligible must be boolean")
        if role_kind in {"reviewer", "orchestrator"} and primary_eligible is not False:
            errors.append(f"{_rel_source(path)} {role_kind} must set primary_eligible=false")
        if role_kind in {"specialist", "helper"} and primary_eligible is not True:
            errors.append(f"{_rel_source(path)} {role_kind} must set primary_eligible=true")
        if execution_class == "specialist" and primary_eligible is not True:
            errors.append(f"{_rel_source(path)} specialist execution_class must set primary_eligible=true")
        developer_instructions = data.get("developer_instructions")
        if isinstance(developer_instructions, str) and developer_instructions.strip():
            errors.extend(validate_developer_instruction_markers(path, developer_instructions))
            errors.extend(validate_developer_instruction_role_override(path, data))

        name = data.get("name")
        if not isinstance(name, str) or not name.strip():
            continue
        if name in seen_names:
            errors.append(f"duplicate agent name {name}: {_rel_source(seen_names[name])} and {_rel_source(path)}")
            continue
        seen_names[name] = path
        agents.append(CanonicalAgent(source_path=path, destination_name=name, body=body, digest=sha256_text(body)))

    if not agents:
        errors.append("no canonical agent TOMLs found")
    return agents, errors


def _role_names_from_list(values: Any) -> set[str]:
    """Return non-empty role names from a JSON list value."""
    if not isinstance(values, list):
        return set()
    return {value.strip() for value in values if isinstance(value, str) and value.strip()}


def _role_name_from_value(value: Any) -> str | None:
    """Return one role name from a JSON scalar value."""
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def load_platform_role_catalog_roles(
    catalog_path: Path = PLATFORM_ROLE_CATALOG,
) -> tuple[set[str], set[str], list[str]]:
    """Load subagents roles catalog role declarations and references."""
    errors: list[str] = []
    try:
        data = json.loads(catalog_path.read_text(encoding="utf-8"))
    except OSError as exc:
        return set(), set(), [f"subagents roles catalog read error: {catalog_path}: {exc}"]
    except json.JSONDecodeError as exc:
        return set(), set(), [f"subagents roles catalog JSON parse error: {catalog_path}: {exc}"]

    if not isinstance(data, dict):
        return set(), set(), ["subagents roles catalog root must be a JSON object"]

    declared_roles: set[str] = set()
    roles = data.get("roles")
    if not isinstance(roles, list):
        errors.append("subagents roles catalog roles must be a list")
    else:
        for index, role in enumerate(roles):
            if not isinstance(role, dict):
                errors.append(f"subagents roles catalog roles[{index}] must be an object")
                continue
            name = _role_name_from_value(role.get("name"))
            if name is None:
                errors.append(f"subagents roles catalog roles[{index}] missing name")
                continue
            declared_roles.add(name)

    referenced_roles: set[str] = set()

    platform_parts = data.get("platform_parts", [])
    if not isinstance(platform_parts, list):
        errors.append("subagents roles catalog platform_parts must be a list")
    else:
        for index, part in enumerate(platform_parts):
            if not isinstance(part, dict):
                errors.append(f"subagents roles catalog platform_parts[{index}] must be an object")
                continue
            required_role = _role_name_from_value(part.get("required_role"))
            if required_role:
                referenced_roles.add(required_role)
            referenced_roles.update(_role_names_from_list(part.get("supporting_roles")))

    workflow_routes = data.get("workflow_routes", [])
    if not isinstance(workflow_routes, list):
        errors.append("subagents roles catalog workflow_routes must be a list")
    else:
        for index, route in enumerate(workflow_routes):
            if not isinstance(route, dict):
                errors.append(f"subagents roles catalog workflow_routes[{index}] must be an object")
                continue
            referenced_roles.update(_role_names_from_list(route.get("required_roles")))

    route_regression_checks = data.get("route_regression_checks", [])
    if not isinstance(route_regression_checks, list):
        errors.append("subagents roles catalog route_regression_checks must be a list")
    else:
        for index, check in enumerate(route_regression_checks):
            if not isinstance(check, dict):
                errors.append(f"subagents roles catalog route_regression_checks[{index}] must be an object")
                continue
            for field in ("required_role", "expected_role"):
                role_name = _role_name_from_value(check.get(field))
                if role_name:
                    referenced_roles.add(role_name)

    return declared_roles, referenced_roles, errors


def _expected_mapping_role_kind(coverage_kind: str | None) -> str | None:
    if coverage_kind == "domain_orchestrator_profile":
        return "orchestrator"
    if coverage_kind == "workflow_helper_profile":
        return "helper"
    return None


def _expected_mapping_primary_eligible(coverage_kind: str | None) -> bool | None:
    if coverage_kind == "domain_orchestrator_profile":
        return False
    if coverage_kind == "workflow_helper_profile":
        return True
    return None


def load_platform_role_catalog_agent_classification(
    catalog_path: Path = PLATFORM_ROLE_CATALOG,
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    """Load expected top-level agent classifications from the subagents roles catalog."""
    errors: list[str] = []
    try:
        data = json.loads(catalog_path.read_text(encoding="utf-8"))
    except OSError as exc:
        return {}, [f"subagents roles catalog read error: {catalog_path}: {exc}"]
    except json.JSONDecodeError as exc:
        return {}, [f"subagents roles catalog JSON parse error: {catalog_path}: {exc}"]
    if not isinstance(data, dict):
        return {}, ["subagents roles catalog root must be a JSON object"]

    expected: dict[str, dict[str, Any]] = {}
    roles = data.get("roles", [])
    if isinstance(roles, list):
        for index, role in enumerate(roles):
            if not isinstance(role, dict):
                continue
            agent_file = role.get("agent_file")
            name = role.get("name")
            if not isinstance(agent_file, str) or not agent_file:
                continue
            expected[agent_file] = {
                "name": name,
                "role_kind": role.get("role_kind"),
                "execution_class": role.get("execution_class"),
                "primary_eligible": role.get("primary_eligible"),
                "source": f"roles[{index}]",
            }

    mappings = data.get("agent_profile_mappings", [])
    if isinstance(mappings, list):
        for index, mapping in enumerate(mappings):
            if not isinstance(mapping, dict):
                continue
            agent_file = mapping.get("agent_file")
            coverage_kind = mapping.get("coverage_kind")
            if not isinstance(agent_file, str) or not agent_file:
                continue
            if agent_file in expected:
                errors.append(f"agent classification duplicate agent_file: {agent_file}")
                continue
            expected_role_kind = _expected_mapping_role_kind(coverage_kind if isinstance(coverage_kind, str) else None)
            expected_primary_eligible = _expected_mapping_primary_eligible(
                coverage_kind if isinstance(coverage_kind, str) else None
            )
            if expected_role_kind is None or expected_primary_eligible is None:
                errors.append(f"agent profile mapping {agent_file} has unsupported coverage_kind: {coverage_kind}")
                continue
            expected[agent_file] = {
                "name": mapping.get("profile_name"),
                "role_kind": expected_role_kind,
                "execution_class": mapping.get("execution_class"),
                "primary_eligible": expected_primary_eligible,
                "source": f"agent_profile_mappings[{index}]",
            }

    return expected, errors


def validate_role_agent_alignment(
    agents: list[CanonicalAgent],
    catalog_path: Path = PLATFORM_ROLE_CATALOG,
) -> list[str]:
    """Validate that catalog roles and profile mappings align with agent TOMLs."""
    declared_roles, referenced_roles, errors = load_platform_role_catalog_roles(catalog_path)
    agent_names = {agent.destination_name for agent in agents}
    expected_classification, classification_errors = load_platform_role_catalog_agent_classification(catalog_path)
    errors.extend(classification_errors)
    agents_by_file = {agent.source_path.relative_to(PLUGIN_ROOT).as_posix(): agent for agent in agents}

    for role_name in sorted(declared_roles - agent_names):
        errors.append(f"platform role {role_name} has no canonical agent TOML")
    for role_name in sorted(referenced_roles - declared_roles):
        errors.append(f"platform role reference {role_name} is not declared in catalog roles")
    for role_name in sorted(referenced_roles - agent_names):
        errors.append(f"platform role reference {role_name} has no canonical agent TOML")
    for agent_file in sorted(set(agents_by_file) - set(expected_classification)):
        errors.append(f"canonical agent {agent_file} has no catalog role or profile mapping")
    for agent_file in sorted(set(expected_classification) - set(agents_by_file)):
        errors.append(f"catalog agent {agent_file} has no canonical agent TOML")
    for agent_file in sorted(set(agents_by_file) & set(expected_classification)):
        agent = agents_by_file[agent_file]
        data = tomllib.loads(agent.body)
        expected = expected_classification[agent_file]
        for field in ("role_kind", "execution_class", "primary_eligible"):
            if data.get(field) != expected.get(field):
                errors.append(
                    f"{agent_file} {field} {data.get(field)!r} must match "
                    f"{expected['source']} expected {expected.get(field)!r}"
                )
        if isinstance(expected.get("name"), str) and data.get("name") != expected["name"]:
            errors.append(f"{agent_file} name {data.get('name')!r} must match {expected['source']} {expected['name']!r}")

    return errors


def target_dir_for(target: str, *, home: Path, repo_root: Path) -> Path:
    """Return the Codex custom-agent directory for a target."""
    if target == "user":
        return home / USER_TARGET_REL
    if target == "repo":
        return repo_root / REPO_TARGET_REL
    raise ValueError(f"unsupported target: {target}")


def expected_content(agent: CanonicalAgent) -> str:
    """Return the managed target file content for one canonical agent."""
    source = _rel_source(agent.source_path)
    return (
        f"{MANAGED_HEADER}\n"
        f"{SOURCE_HEADER}{source}\n"
        f"{DIGEST_HEADER}{agent.digest}\n"
        f"{MANAGED_DIGEST_HEADER}{sha256_text(agent.body)}\n\n"
        f"{agent.body}"
    )


def _header_value(text: str, prefix: str) -> str | None:
    for line in text.splitlines()[:8]:
        if line.startswith(prefix):
            return line.removeprefix(prefix).strip()
    return None


def _is_managed(text: str) -> bool:
    return text.startswith(MANAGED_HEADER + "\n")


def _source_exists(source_value: str) -> bool:
    source_path = Path(source_value)
    if not source_path.is_absolute():
        source_path = PLUGIN_ROOT / source_path
    try:
        source_path.resolve().relative_to(CANONICAL_AGENT_DIR.resolve())
    except ValueError:
        return False
    return source_path.is_file()


def check_registration(
    *,
    target: str,
    target_dir: Path,
    agents: list[CanonicalAgent],
    schema_errors: list[str],
) -> dict[str, Any]:
    """Return a read-only registration drift packet."""
    expected = {agent.destination_file: agent for agent in agents}
    missing: list[str] = []
    stale: list[str] = []
    local_edits: list[str] = []
    extra: list[str] = []
    registered_agents = 0

    for file_name, agent in expected.items():
        path = target_dir / file_name
        wanted = expected_content(agent)
        if not path.exists():
            missing.append(file_name)
            continue
        actual = path.read_text(encoding="utf-8")
        if not _is_managed(actual):
            local_edits.append(file_name)
            continue
        registered_agents += 1
        if actual != wanted:
            stale.append(file_name)

    if target_dir.is_dir():
        for path in sorted(target_dir.glob("*.toml")):
            if path.name in expected:
                continue
            text = path.read_text(encoding="utf-8")
            if _is_managed(text):
                extra.append(path.name)

    status = "pass"
    if schema_errors or missing or stale or extra or local_edits:
        status = "fail"

    agent_type_names = sorted(agent.destination_name for agent in agents)
    return {
        "status": status,
        "target": target,
        "target_dir": str(target_dir),
        "canonical_agents": len(agents),
        "registered_agents": registered_agents,
        "missing": missing,
        "stale": stale,
        "extra": extra,
        "local_edits": local_edits,
        "schema_errors": schema_errors,
        "sync_command": f"python3 scripts/agent_registration_sync.py sync --target {target}",
        "runtime_tool_schema_checkpoint": {
            "status": TOOL_SCHEMA_REFRESH_REQUIRED_STATUS,
            "disk_registration_only": True,
            "active_tool_schema_verified": False,
            "agent_type_names": agent_type_names,
            "unavailable_agent_type_cache_required": True,
            "retry_direct_spawn_before_refresh_allowed": False,
            "refresh_required_before_direct_spawn": True,
            "operator_message": (
                "Disk registration does not prove active multi_agent tool schema freshness; "
                "refresh the Codex session or verify the active tool schema before direct spawn."
            ),
        },
    }


def sync_registration(packet: dict[str, Any], agents: list[CanonicalAgent], target_dir: Path) -> dict[str, Any]:
    """Materialize managed agent files without overwriting unmanaged local files."""
    if packet["schema_errors"]:
        raise ValueError("canonical agent schema errors block sync")
    if packet["local_edits"]:
        raise ValueError("unmanaged target files block sync: " + ", ".join(packet["local_edits"]))
    if packet["extra"]:
        raise ValueError("stale managed target files block sync cleanup: " + ", ".join(packet["extra"]))

    target_dir.mkdir(parents=True, exist_ok=True)
    for agent in agents:
        path = target_dir / agent.destination_file
        content = expected_content(agent)
        if path.exists():
            actual = path.read_text(encoding="utf-8")
            if not _is_managed(actual):
                raise ValueError(f"unmanaged target file blocks sync: {path}")
            if actual == content:
                continue
        path.write_text(content, encoding="utf-8")

    return check_registration(target=packet["target"], target_dir=target_dir, agents=agents, schema_errors=[])


def print_packet(packet: dict[str, Any], *, as_json: bool) -> None:
    """Print a packet as JSON or concise text."""
    if as_json:
        print(json.dumps(packet, indent=2, sort_keys=True))
        return
    if packet.get("schema") == "bears-agent-role-audit.v1":
        print(f"status: {packet['status']}")
        print(f"schema: {packet['schema']}")
        print(f"audit_order: {packet['audit_order']}")
        print(f"canonical_agents: {packet['canonical_agents']}")
        print(f"failed_agents: {packet['failed_agents']}")
        for item in packet["sequence"]:
            print(
                f"{item['index']}. {item['agent_file']} "
                f"name={item['name']} role_kind={item['role_kind']} "
                f"execution_class={item['execution_class']} status={item['status']}"
            )
        for error in packet.get("schema_errors", []):
            print(f"schema_error: {error}")
        return
    print(f"status: {packet['status']}")
    print(f"target: {packet['target']}")
    print(f"target_dir: {packet['target_dir']}")
    print(f"canonical_agents: {packet['canonical_agents']}")
    print(f"registered_agents: {packet['registered_agents']}")
    for key in ("missing", "stale", "extra", "local_edits", "schema_errors"):
        values = packet[key]
        print(f"{key}: {len(values)}")
        for value in values:
            print(f"  - {value}")
    print(f"sync_command: {packet['sync_command']}")
    checkpoint = packet["runtime_tool_schema_checkpoint"]
    print(f"runtime_tool_schema_checkpoint: {checkpoint['status']}")
    print(f"active_tool_schema_verified: {str(checkpoint['active_tool_schema_verified']).lower()}")
    print(
        "retry_direct_spawn_before_refresh_allowed: "
        f"{str(checkpoint['retry_direct_spawn_before_refresh_allowed']).lower()}"
    )


def _common_target(args: argparse.Namespace) -> tuple[list[CanonicalAgent], list[str], Path]:
    agents, errors = load_canonical_agents(CANONICAL_AGENT_DIR)
    target_dir = target_dir_for(args.target, home=args.home.expanduser(), repo_root=args.repo_root)
    return agents, errors, target_dir


def cmd_check(args: argparse.Namespace) -> int:
    """Run read-only registration drift detection."""
    agents, errors, target_dir = _common_target(args)
    packet = check_registration(target=args.target, target_dir=target_dir, agents=agents, schema_errors=errors)
    print_packet(packet, as_json=args.json)
    return 0 if packet["status"] == "pass" else 1


def cmd_sync(args: argparse.Namespace) -> int:
    """Sync canonical agent TOMLs to the selected Codex agent target."""
    agents, errors, target_dir = _common_target(args)
    packet = check_registration(target=args.target, target_dir=target_dir, agents=agents, schema_errors=errors)
    final_packet = sync_registration(packet, agents, target_dir)
    print_packet(final_packet, as_json=args.json)
    return 0 if final_packet["status"] == "pass" else 1


def cmd_validate(args: argparse.Namespace) -> int:
    """Validate canonical agent schema and a temporary repo sync cycle."""
    agents, errors = load_canonical_agents(CANONICAL_AGENT_DIR)
    role_alignment_errors = validate_role_agent_alignment(agents)
    validation_errors = [*errors, *role_alignment_errors]
    if validation_errors:
        for error in validation_errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    names = [agent.destination_name for agent in agents]
    if len(names) != len(set(names)):
        print("ERROR: duplicate destination agent names", file=sys.stderr)
        return 1
    print(f"agent registration sync ok: {len(agents)} canonical agents")
    return 0


def cmd_audit_roles(args: argparse.Namespace) -> int:
    """Run deterministic sequential role audit over every canonical agent."""
    agents, errors = load_canonical_agents(CANONICAL_AGENT_DIR)
    packet = build_role_audit_packet(agents, errors)
    print_packet(packet, as_json=args.json)
    return 0 if packet["status"] == "pass" else 1


def build_parser() -> argparse.ArgumentParser:
    """Build the command line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    def add_target_options(subparser: argparse.ArgumentParser) -> None:
        subparser.add_argument("--target", choices=ALLOWED_TARGETS, default="user")
        subparser.add_argument("--home", type=Path, default=Path.home())
        subparser.add_argument("--repo-root", type=Path, default=PLUGIN_ROOT)
        subparser.add_argument("--json", action="store_true")

    check_parser = subparsers.add_parser("check")
    add_target_options(check_parser)
    check_parser.set_defaults(func=cmd_check)

    sync_parser = subparsers.add_parser("sync")
    add_target_options(sync_parser)
    sync_parser.set_defaults(func=cmd_sync)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.set_defaults(func=cmd_validate)

    audit_roles_parser = subparsers.add_parser("audit-roles")
    audit_roles_parser.add_argument("--json", action="store_true")
    audit_roles_parser.set_defaults(func=cmd_audit_roles)
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the CLI."""
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
