#!/usr/bin/env python3
"""Install and run shared @bears git hook entrypoints."""
from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
def default_workspace_root() -> Path:
    if PLUGIN_ROOT.name == "bears" and PLUGIN_ROOT.parent.name == "plugins":
        return PLUGIN_ROOT.parents[1]
    return PLUGIN_ROOT.parent


DEFAULT_WORKSPACE_ROOT = default_workspace_root()
PROOF_SCHEMA = PLUGIN_ROOT / "assets/schemas/effective-hooks-proof.v1.schema.json"
CATALOG = PLUGIN_ROOT / "assets/catalog/git-hook-bootstrap.v1.json"
HOOKS = ("pre-commit", "post-commit")
GIT_HOOK_ENV_KEYS = ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_PREFIX", "GIT_COMMON_DIR")

if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))
from scripts.local_json_schema import validate_json_schema
from scripts import validation_queue


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def clean_env() -> dict[str, str]:
    env = os.environ.copy()
    for key in GIT_HOOK_ENV_KEYS:
        env.pop(key, None)
    return env


def run_command(argv: list[str], *, cwd: Path, timeout: int = 10) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            argv,
            cwd=str(cwd),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=timeout,
            env=clean_env(),
        )
    except FileNotFoundError:
        return 127, "command not found"
    except subprocess.TimeoutExpired:
        return 124, "timeout"
    if proc.returncode == 0:
        return 0, "ok"
    return proc.returncode, "command failed"


def git_text(repo_path: Path, args: list[str], *, timeout: int = 10) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=str(repo_path),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        timeout=timeout,
        env=clean_env(),
    )
    if proc.returncode != 0:
        raise RuntimeError("git command failed")
    return proc.stdout.strip()


def resolve_repo_path(repo_path: str | None) -> Path:
    base = Path(repo_path).resolve() if repo_path else Path.cwd().resolve()
    top = git_text(base, ["rev-parse", "--show-toplevel"])
    return Path(top).resolve()


def hooks_dir(repo_path: Path) -> Path:
    raw = git_text(repo_path, ["rev-parse", "--git-path", "hooks"])
    path = Path(raw)
    return path if path.is_absolute() else (repo_path / path).resolve()


def repo_id(repo_path: Path, workspace_root: Path) -> str:
    try:
        rel = repo_path.resolve().relative_to(workspace_root.resolve())
        value = rel.as_posix() or "workspace-root"
    except ValueError:
        value = repo_path.name
    safe = "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in value)
    return safe or "repo"


def runtime_paths(repo_path: Path, workspace_root: Path, commit_sha: str | None = None) -> dict[str, str]:
    rid = repo_id(repo_path, workspace_root)
    commit_part = commit_sha or "pending"
    return {
        "effective_hooks": str(PLUGIN_ROOT / "runtime/effective-hooks" / rid / "effective-hooks-proof.v1.json"),
        "validation_jobs": str(PLUGIN_ROOT / "runtime/validation-jobs" / commit_part),
        "validation_state": str(PLUGIN_ROOT / "runtime/validation-state" / commit_part / "validation-state.v1.json"),
    }


def sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def hook_body(hook_name: str, *, workspace_root: Path, repo_path: Path) -> str:
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "# @bears shared git hook entrypoint. Generated by scripts/bears_git_hook.py.",
            f"exec python3 {sh_quote(str(PLUGIN_ROOT / 'scripts/bears_git_hook.py'))} run --hook {sh_quote(hook_name)} --workspace-root {sh_quote(str(workspace_root))} --repo-path {sh_quote(str(repo_path))}",
            "",
        ]
    )


def hook_entries(repo_path: Path, workspace_root: Path) -> list[dict[str, Any]]:
    hdir = hooks_dir(repo_path)
    entries: list[dict[str, Any]] = []
    runner = str(PLUGIN_ROOT / "scripts/bears_git_hook.py")
    for name in HOOKS:
        path = hdir / name
        text = path.read_text(encoding="utf-8") if path.exists() else ""
        entries.append(
            {
                "name": name,
                "entrypoint_path": str(path),
                "entrypoint_exists": path.exists(),
                "entrypoint_executable": path.exists() and bool(path.stat().st_mode & stat.S_IXUSR),
                "runner_match": runner in text and "@bears" in text,
                "mode": "cheap_blocking_checks" if name == "pre-commit" else "enqueue_validation",
            }
        )
    return entries


def build_proof(repo_path: Path, workspace_root: Path, commit_sha: str | None = None) -> dict[str, Any]:
    hooks = hook_entries(repo_path, workspace_root)
    status = "pass" if all(h["entrypoint_exists"] and h["entrypoint_executable"] and h["runner_match"] for h in hooks) else "fail"
    return {
        "schema": "bears-effective-hooks-proof.v1",
        "version": "1",
        "updated_at": utc_now(),
        "status": status,
        "workspace_root": str(workspace_root),
        "repo_path": str(repo_path),
        "repo_id": repo_id(repo_path, workspace_root),
        "plugin_reference": "@bears",
        "runner_script": str(PLUGIN_ROOT / "scripts/bears_git_hook.py"),
        "commit_sha": commit_sha,
        "hooks": hooks,
        "runtime_paths": runtime_paths(repo_path, workspace_root, commit_sha),
        "closeout_consumers": ["hooks/stop_closeout_guard.py", "bears_doctor#388"],
    }


def write_json(path: Path, packet: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(packet, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def write_effective_proof(repo_path: Path, workspace_root: Path, commit_sha: str | None = None) -> tuple[Path, dict[str, Any]]:
    packet = build_proof(repo_path, workspace_root, commit_sha)
    proof_path = Path(packet["runtime_paths"]["effective_hooks"])
    return write_json(proof_path, packet), packet


def event(decision: str, reason: str, **extra: Any) -> dict[str, Any]:
    packet: dict[str, Any] = {
        "schema": "bears-git-hook-event.v1",
        "decision": decision,
        "reason": reason,
        "plugin_reference": "@bears",
    }
    packet.update(extra)
    return packet


def print_event(packet: dict[str, Any]) -> None:
    print(json.dumps(packet, indent=2, sort_keys=True))


def install_hooks(repo_path: Path, workspace_root: Path, *, force: bool = False) -> dict[str, Any]:
    hdir = hooks_dir(repo_path)
    hdir.mkdir(parents=True, exist_ok=True)
    installed: list[str] = []
    for name in HOOKS:
        path = hdir / name
        body = hook_body(name, workspace_root=workspace_root, repo_path=repo_path)
        if path.exists() and path.read_text(encoding="utf-8") != body and not force:
            return event("deny", "hook exists with different content", hook=name, entrypoint_path=str(path))
        path.write_text(body, encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        installed.append(str(path))
    proof_path, proof = write_effective_proof(repo_path, workspace_root)
    return event("allow", "hooks installed", repo_path=str(repo_path), installed=installed, proof_path=str(proof_path), proof_status=proof["status"])


def current_commit(repo_path: Path) -> str | None:
    try:
        return git_text(repo_path, ["rev-parse", "--verify", "HEAD"])
    except Exception:
        return None


def changed_files_for_commit(repo_path: Path, commit_sha: str) -> list[str]:
    return validation_queue.changed_files_from_git(repo_path, commit_sha)


def run_hook(hook_name: str, repo_path: Path, workspace_root: Path) -> tuple[int, dict[str, Any]]:
    if hook_name not in HOOKS:
        return 2, event("deny", "unsupported hook", hook=hook_name)
    commit_sha = current_commit(repo_path) if hook_name == "post-commit" else None
    proof_path, proof = write_effective_proof(repo_path, workspace_root, commit_sha)
    if hook_name == "pre-commit":
        code, summary = run_command(["git", "diff", "--cached", "--check", "--no-ext-diff"], cwd=repo_path, timeout=10)
        if repo_path.resolve() == PLUGIN_ROOT.resolve():
            registry_code, registry_summary = run_command([sys.executable, "scripts/artifact_registry.py", "check-added-files", "--staged"], cwd=PLUGIN_ROOT, timeout=10)
            decision_code, decision_summary = run_command([sys.executable, "scripts/decision_ledger.py", "check-required", "--staged"], cwd=PLUGIN_ROOT, timeout=10)
        else:
            registry_code, registry_summary = 0, "not_applicable: non-plugin repo"
            decision_code, decision_summary = 0, "not_applicable: non-plugin repo"
        decision = "allow" if code == 0 and registry_code == 0 and decision_code == 0 and proof["status"] == "pass" else "deny"
        reason = "cheap checks passed" if decision == "allow" else "cheap checks failed"
        return (0 if decision == "allow" else 1), event(decision, reason, hook=hook_name, repo_path=str(repo_path), worktree_path=str(repo_path), commit_sha=commit_sha, proof_path=str(proof_path), check_exit_code=code, check_summary=summary, artifact_registry_exit_code=registry_code, artifact_registry_summary=registry_summary, decision_ledger_exit_code=decision_code, decision_ledger_summary=decision_summary)
    if not commit_sha:
        return 2, event("deny", "commit sha unavailable", hook=hook_name, repo_path=str(repo_path), proof_path=str(proof_path))
    changed = changed_files_for_commit(repo_path, commit_sha)
    job_path, state_path, job = validation_queue.enqueue_job(commit_sha, changed, repo_path=repo_path, source="post-commit")
    return 0, event("allow", "validation enqueued", hook=hook_name, repo_path=str(repo_path), worktree_path=str(repo_path), commit_sha=commit_sha, proof_path=str(proof_path), job_path=str(job_path), state_path=str(state_path), worker_spawn="not_started", worker_spawn_reason="hooks enqueue only; async workers are started outside hook hot paths")


def load_catalog() -> dict[str, Any]:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def validate_catalog() -> list[str]:
    try:
        packet = load_catalog()
    except Exception as exc:
        return [f"cannot read catalog: {exc}"]
    errors: list[str] = []
    if packet.get("schema") != "bears-git-hook-bootstrap.v1":
        errors.append("catalog schema must be bears-git-hook-bootstrap.v1")
    if packet.get("plugin_reference") != "@bears":
        errors.append("plugin_reference must be @bears")
    if packet.get("default_workspace_root") != "<generated-local-config:workspace_root>":
        errors.append("default_workspace_root must point to generated local config workspace_root")
    if packet.get("shared_runner") != "scripts/bears_git_hook.py":
        errors.append("shared_runner must be scripts/bears_git_hook.py")
    if not (PLUGIN_ROOT / "scripts/bears_git_hook.py").exists():
        errors.append("shared runner file is missing")

    command_names = {command.get("name") for command in packet.get("commands", []) if isinstance(command, dict)}
    required_commands = {"install", "run", "verify", "write-proof", "validate-proof", "validate"}
    if command_names != required_commands:
        errors.append("commands must include install, run, verify, write-proof, validate-proof, validate")

    hook_names = {hook.get("name") for hook in packet.get("thin_hooks", []) if isinstance(hook, dict)}
    if hook_names != set(HOOKS):
        errors.append("thin_hooks must include pre-commit and post-commit")
    for hook in packet.get("thin_hooks", []):
        if not isinstance(hook, dict):
            errors.append("thin_hooks entries must be objects")
            continue
        forbidden = set(hook.get("forbidden_actions", []))
        if "run_test_suite" not in forbidden:
            errors.append(f"{hook.get('name')} must forbid run_test_suite")
        if "print_unbounded_output" not in forbidden:
            errors.append(f"{hook.get('name')} must forbid print_unbounded_output")
        if "solve_github_issue" not in forbidden:
            errors.append(f"{hook.get('name')} must forbid solve_github_issue")
    post_hook = next((hook for hook in packet.get("thin_hooks", []) if isinstance(hook, dict) and hook.get("name") == "post-commit"), {})
    if "write_validation_job" not in post_hook.get("allowed_actions", []):
        errors.append("post-commit must write validation jobs")

    bounded_spawn = packet.get("bounded_spawn", {})
    if not isinstance(bounded_spawn, dict):
        errors.append("bounded_spawn must be an object")
    else:
        if bounded_spawn.get("auto_start") is not False:
            errors.append("bounded_spawn.auto_start must be false")
        if bounded_spawn.get("enabled") is not False:
            errors.append("bounded_spawn.enabled must be false for hook hot paths")
        if int(bounded_spawn.get("timeout_seconds", 999)) > 5:
            errors.append("bounded_spawn timeout must be <= 5 seconds")
    if packet.get("stdout_policy") != "single_bounded_json_event":
        errors.append("stdout_policy must be single_bounded_json_event")
    if packet.get("proof_schema") != "assets/schemas/effective-hooks-proof.v1.schema.json":
        errors.append("proof_schema must point to effective-hooks-proof.v1.schema.json")
    return errors


def validate_proof_file(path: Path) -> list[str]:
    try:
        packet = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return [f"cannot read proof: {exc}"]
    errors = validate_json_schema(packet, PROOF_SCHEMA, "proof")
    if packet.get("status") != "pass":
        errors.append("proof.status must be pass")
    hooks = packet.get("hooks", [])
    if isinstance(hooks, list):
        seen = {h.get("name") for h in hooks if isinstance(h, dict)}
        if seen != set(HOOKS):
            errors.append("proof must include pre-commit and post-commit")
        for hook in hooks:
            if isinstance(hook, dict) and not (hook.get("entrypoint_exists") and hook.get("entrypoint_executable") and hook.get("runner_match")):
                errors.append(f"hook not effective: {hook.get('name')}")
    return errors


def args_repo_workspace(args: argparse.Namespace) -> tuple[Path, Path]:
    workspace_root = Path(getattr(args, "workspace_root", None) or DEFAULT_WORKSPACE_ROOT).resolve()
    repo_path = resolve_repo_path(getattr(args, "repo_path", None))
    return repo_path, workspace_root


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    install = sub.add_parser("install")
    install.add_argument("--workspace-root", default=str(DEFAULT_WORKSPACE_ROOT))
    install.add_argument("--scope", choices=["current"], default="current")
    install.add_argument("--repo-path")
    install.add_argument("--force", action="store_true")
    run = sub.add_parser("run")
    run.add_argument("--hook", required=True)
    run.add_argument("--workspace-root", default=str(DEFAULT_WORKSPACE_ROOT))
    run.add_argument("--repo-path")
    verify = sub.add_parser("verify")
    verify.add_argument("--repo-path", required=True)
    verify.add_argument("--workspace-root", default=str(DEFAULT_WORKSPACE_ROOT))
    proof = sub.add_parser("write-proof")
    proof.add_argument("--repo-path", required=True)
    proof.add_argument("--workspace-root", default=str(DEFAULT_WORKSPACE_ROOT))
    validate = sub.add_parser("validate-proof")
    validate.add_argument("--proof", required=True)
    sub.add_parser("validate")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "validate":
        errors = validate_catalog()
        print_event({"schema": "bears-git-hook-bootstrap-validation.v1", "status": "pass" if not errors else "fail", "errors": errors})
        return 0 if not errors else 1
    if args.command == "validate-proof":
        errors = validate_proof_file(Path(args.proof))
        print_event({"schema": "bears-effective-hooks-proof-validation.v1", "status": "pass" if not errors else "fail", "errors": errors})
        return 0 if not errors else 1
    repo_path, workspace_root = args_repo_workspace(args)
    if args.command == "install":
        packet = install_hooks(repo_path, workspace_root, force=bool(args.force))
        print_event(packet)
        return 0 if packet["decision"] == "allow" else 2
    if args.command == "run":
        code, packet = run_hook(args.hook, repo_path, workspace_root)
        print_event(packet)
        return code
    if args.command == "verify":
        packet = build_proof(repo_path, workspace_root, current_commit(repo_path))
        print_event(event("allow" if packet["status"] == "pass" else "deny", "effective hook proof checked", repo_path=str(repo_path), status=packet["status"], hooks=packet["hooks"]))
        return 0 if packet["status"] == "pass" else 1
    if args.command == "write-proof":
        proof_path, packet = write_effective_proof(repo_path, workspace_root, current_commit(repo_path))
        print_event(event("allow" if packet["status"] == "pass" else "deny", "effective hook proof written", repo_path=str(repo_path), status=packet["status"], proof_path=str(proof_path)))
        return 0 if packet["status"] == "pass" else 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
