#!/usr/bin/env python3
"""Materialize Bears canonical agent TOMLs into OpenCode repo agents."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = PLUGIN_ROOT.parents[1]
CANONICAL_AGENT_DIR = PLUGIN_ROOT / "agents"
REPO_TARGET_REL = Path(".opencode/agent")
MANAGED_BY = "opencode_agent_sync.py"
MANAGED_COMMENT = "<!-- Generated by Bears opencode_agent_sync.py. -->"
SOURCE_PATH_PREFIX = "<!-- Source-Path: "
SOURCE_DIGEST_PREFIX = "<!-- Source-Digest-SHA256: "
MANAGED_DIGEST_PREFIX = "<!-- Managed-Digest-SHA256: "
REQUIRED_FIELDS = (
    "name",
    "description",
    "role_kind",
    "execution_class",
    "primary_eligible",
    "model",
    "model_reasoning_effort",
    "sandbox_mode",
    "developer_instructions",
)


@dataclass(frozen=True)
class Agent:
    source_path: Path
    rel_source: str
    data: dict[str, Any]
    source_text: str
    source_digest: str

    @property
    def name(self) -> str:
        return str(self.data["name"])

    @property
    def target_name(self) -> str:
        return f"{self.name}.md"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def bool_yaml(value: bool) -> str:
    return "true" if value else "false"


def rel_source(path: Path) -> str:
    return path.resolve().relative_to(PLUGIN_ROOT.resolve()).as_posix()


def load_agents() -> tuple[list[Agent], list[str]]:
    errors: list[str] = []
    agents: list[Agent] = []
    seen: dict[str, str] = {}
    for path in sorted(CANONICAL_AGENT_DIR.glob("*.toml")):
        text = path.read_text(encoding="utf-8")
        source = rel_source(path)
        try:
            data = tomllib.loads(text)
        except tomllib.TOMLDecodeError as exc:
            errors.append(f"{source}: TOML parse error: {exc}")
            continue
        for field in REQUIRED_FIELDS:
            if field not in data:
                errors.append(f"{source}: missing {field}")
        name = data.get("name")
        if not isinstance(name, str) or not name.strip():
            errors.append(f"{source}: name must be a non-empty string")
            continue
        if name in seen:
            errors.append(f"{source}: duplicate name {name} also in {seen[name]}")
            continue
        seen[name] = source
        agents.append(Agent(path, source, data, text, sha256_text(text)))
    if not agents:
        errors.append(f"no canonical agents found under {CANONICAL_AGENT_DIR}")
    return agents, errors


def target_root(target: str) -> Path:
    if target == "repo":
        return WORKSPACE_ROOT / REPO_TARGET_REL
    if target == "user":
        root = os.environ.get("OPENCODE_CONFIG_DIR")
        if root:
            return Path(root).expanduser() / "agent"
        return Path.home() / ".config" / "opencode" / "agent"
    raise ValueError(f"unsupported target: {target}")


def render_agent(agent: Agent) -> str:
    data = agent.data
    model = str(data["model"])
    if not model.startswith("openai/"):
        model = f"openai/{model}"
    primary = bool(data["primary_eligible"])
    source_block = (
        f"{MANAGED_COMMENT}\n"
        f"<!-- Source-Path: {agent.rel_source} -->\n"
        f"<!-- Source-Digest-SHA256: {agent.source_digest} -->\n"
    )
    body_without_managed_digest = f"""---
description: {yaml_quote(str(data['description']))}
mode: subagent
model: {model}
hidden: true
color: primary
options:
  bears_generated_by: {yaml_quote(MANAGED_BY)}
  bears_source_path: {yaml_quote(agent.rel_source)}
  bears_source_digest: {yaml_quote(agent.source_digest)}
  bears_role_kind: {yaml_quote(str(data['role_kind']))}
  bears_execution_class: {yaml_quote(str(data['execution_class']))}
  bears_primary_eligible: {bool_yaml(primary)}
  bears_sandbox_mode: {yaml_quote(str(data['sandbox_mode']))}
permission:
  edit:
    "*": deny
    "/srv/bears/**": ask
  bash:
    "*": ask
    "python3 /srv/bears/plugins/bears/scripts/platform_roles.py route *": allow
    "python3 /srv/bears/plugins/bears/scripts/platform_roles.py audit *": allow
  external_directory:
    "*": deny
    "/srv/bears/**": allow
---

{source_block}
# {agent.name}

This OpenCode agent is generated from the canonical Bears TOML role. Do not edit it directly; update the source TOML and rerun `opencode_agent_sync.py sync`.

## Bears Role Instructions

{str(data['developer_instructions']).rstrip()}
"""
    managed_digest = sha256_text(body_without_managed_digest)
    return body_without_managed_digest.replace(
        f"{source_block}\n# {agent.name}",
        f"{source_block}<!-- Managed-Digest-SHA256: {managed_digest} -->\n\n# {agent.name}",
    )


def managed_metadata(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for key, pattern in {
        "source_path": r"bears_source_path:\s*\"([^\"]+)\"",
        "source_digest": r"bears_source_digest:\s*\"([^\"]+)\"",
        "generated_by": r"bears_generated_by:\s*\"([^\"]+)\"",
    }.items():
        match = re.search(pattern, text)
        if match:
            result[key] = match.group(1)
    if not result.get("source_path"):
        match = re.search(r"<!-- Source-Path: ([^>]+) -->", text)
        if match:
            result["source_path"] = match.group(1).strip()
    if not result.get("source_digest"):
        match = re.search(r"<!-- Source-Digest-SHA256: ([^>]+) -->", text)
        if match:
            result["source_digest"] = match.group(1).strip()
    return result


def check(target: str) -> dict[str, Any]:
    agents, schema_errors = load_agents()
    root = target_root(target)
    expected = {agent.target_name: agent for agent in agents}
    missing: list[str] = []
    stale: list[str] = []
    local_edits: list[str] = []
    extra: list[str] = []
    for name, agent in expected.items():
        path = root / name
        if not path.exists():
            missing.append(name)
            continue
        text = path.read_text(encoding="utf-8")
        meta = managed_metadata(text)
        if meta.get("source_path") != agent.rel_source:
            local_edits.append(name)
            continue
        if meta.get("source_digest") != agent.source_digest:
            stale.append(name)
    if root.exists():
        for path in sorted(root.glob("*.md")):
            if path.name not in expected:
                meta = managed_metadata(path.read_text(encoding="utf-8"))
                if meta.get("generated_by") == MANAGED_BY or "Generated by Bears opencode_agent_sync.py" in path.read_text(encoding="utf-8"):
                    extra.append(path.name)
                else:
                    local_edits.append(path.name)
    status = "pass" if not (schema_errors or missing or stale or extra) else "fail"
    return {
        "schema": "bears-opencode-agent-sync-check.v1",
        "status": status,
        "target": target,
        "target_dir": str(root),
        "canonical_agents": len(agents),
        "missing": missing,
        "stale": stale,
        "extra": extra,
        "local_edits": local_edits,
        "schema_errors": schema_errors,
        "restart_required": bool(missing or stale or extra),
    }


def sync(target: str) -> dict[str, Any]:
    agents, schema_errors = load_agents()
    if schema_errors:
        return {"schema": "bears-opencode-agent-sync-result.v1", "status": "fail", "target": target, "schema_errors": schema_errors, "written": []}
    root = target_root(target)
    root.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    skipped_local_edits: list[str] = []
    for agent in agents:
        path = root / agent.target_name
        rendered = render_agent(agent)
        if path.exists():
            current = path.read_text(encoding="utf-8")
            meta = managed_metadata(current)
            if meta.get("source_path") and meta.get("source_path") != agent.rel_source:
                skipped_local_edits.append(path.name)
                continue
            if meta.get("source_digest") == agent.source_digest and MANAGED_DIGEST_PREFIX in current:
                continue
            if current == rendered:
                continue
        path.write_text(rendered, encoding="utf-8")
        written.append(path.name)
    packet = check(target)
    return {
        "schema": "bears-opencode-agent-sync-result.v1",
        "status": "pass" if not skipped_local_edits and not packet["schema_errors"] else "fail",
        "target": target,
        "target_dir": str(root),
        "canonical_agents": len(agents),
        "written": written,
        "skipped_local_edits": skipped_local_edits,
        "check": packet,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("check", "sync"):
        cmd = sub.add_parser(command)
        cmd.add_argument("--target", choices=("repo", "user"), default="repo")
        cmd.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    packet = check(args.target) if args.command == "check" else sync(args.target)
    if args.json:
        print(json.dumps(packet, indent=2, sort_keys=True))
    else:
        print(f"{packet['schema']} {packet['status']}")
    return 0 if packet.get("status") == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
